### ISSUE TITLE
haskell-src-exts update

### ISSUE THREAD

**Issue by ag-eitilt** [gentoo-haskell/gentoo-haskell#1043]
Now that hoogle-5.0.17.3 is no longer building (`for` in `src/Action/Server.hs` is no longer imported), it's probably time to finish the "Too many packages require <haskell-src-exts-1.21" listed as the reason for masking anything newer.

Interestingly, though, the only newer version of haskell-src-exts in the repo is 1.22.  I've gone through and checked everything which depends on it, in case we could skip directly to that version; the packages which don't have any ebuild accepting either of the newer haskell-src-exts are (note that I wasn't looking at keywording):

- app-emacs/hindent (<1.21, upstream no upper bound -- ebuild needs revision)
- dev-haskell/beam-migrate (<1.22)
- dev-haskell/beam-migrate-cli (<1.21, upstream <1.22 since 2020-01-07 snapshot)
- dev-haskell/beam-postgres (<1.22)
- dev-haskell/derive (<1.21)
- dev-haskell/fay (<1.21, upstream no bound since fay-0.24.0.5)
- dev-haskell/haskell-names (<1.21, upstream <1.22 since haskell-names-0.9.5, <1.23 since haskell-names-0.9.7)
- dev-haskell/hgettext (<1.21)
- dev-haskell/hoogle (<1.21/==1.21 -- hoogle-5.0.17.4 should be deprecated, upstream ==1.21 since hoogle-5.0.17.5, ==1.22 since hoogle-5.0.17.12, <1.24 since hoogle-5.0.17.14)
- dev-haskell/hsx (<1.16 -- deprecated)
- dev-haskell/lambdabot-haskell-plugins (<1.20 via <haskell-src-exts-simple-1.20.1, upstream <1.22 via <haskell-src-exts-simple-1.22 since lambdabot-haskell-plugins-5.2)
- dev-haskell/pointfree (<1.21)
- dev-haskell/reflex (<1.22, upstream <1.23 since reflex-0.6.4)
- dev-haskell/scion-browser (<1.15, upstream <1.16 since scion-browser-0.3.2, <1.17 since scion-browser-0.3.4)
- dev-util/hsdev (<1.18, upstream <1.19.0 since hsdev-0.2.1.0, <1.20.0 since hsdev-0.2.2.0, <1.21.0 since hsdev-0.3.0.0, <1.22.0 since hsdev-0.3.2.3)
- dev-util/packunused (<1.17, upstream <1.20 since packunused-0.1.2)

In summary, that's five that don't even work with the current version of haskell-src-exts (`hsdev`, `hsx`, `lambdabot-haskell-plugins`, `scion-browser`, `packunused`), three of which (`hsx`, `scion-browser`, `packunused`) never will.  Three more (`derive`, `hgettext`, `pointfree`) will stop working if we update, with 21 (direct) reverse dependencies between them.  Looking forward, we have three which already work on 1.21 (`beam-migrate`, `beam-postgres`, `reflex`), and seven more which will work if we update the ebuilds (`beam-migrate-cli`, `fay`, `haskell-names`, `hindent`, `hoogle`, `hsdev`, `lambdabot-haskell-plugins`) -- since only four have any hope of working with 1.22 at the moment (`fay`, `hindent`, `hoogle`, `reflex`) discounting anything currently without an upper bound, it's certainly not time to update to that.

Given that spread, the task seems to me to be:

- [ ] Generate new ebuilds for:
  - ~~>=beam-migrate-cli-0.2.0.0_pre20200107~~ (this has been removed from the tree)
  - [x] fay-0.24.0.5 (just updated ten days ago, may not be stable)
  - [x] >=haskell-names-0.9.5
  - [x] haskell-src-exts-1.21.0 || haskell-src-exts-1.21.1
  - [x] >=hoogle-5.0.17.5 && <hoogle-5.0.17.12
  - [x] >=hsdev-0.3.2.3
  - [x] lambdabot-haskell-plugins-5.2
- [x] Revise hindent-5.3.1 to remove the upper bound (I don't like doing it, but that's following upstream)
- [x] Remove hoogle-5.0.17.4 (which is currently masked anyway)
- [ ] Work with the upstream developers to update:
  - [x] derive (explicitly unmaintained: ndmitchell/derive#36)
        There are only four packages in the repo using it.  It may be better to just remove derive entirely, or we can make sure the upper version bounds are all tight and let it hang on as long as possible.
    - [ ] app-editors/yi only requires it for 0.11.1-r1, which GHC 8.6.5 can't build; the later versions (didn't check whether they compile) don't list it as a requirement and while this is the only one of these four with [reverse dependencies](https://packdeps.haskellers.com/reverse/yi), there's nothing asking for 0.11 specifically -- remove yi-0.11.1-r1
    - [ ] dev-haskell/quickfuzz isn't on Hackage, but even so it's the most lively of any of them with the last activity taking place at the end of 2017; GHC 8.8 will probably kill it, but in the mean time it even still builds, so it can technically stick around if we don't mind keeping the old derive
    - [ ] dev-haskell/scion-browser is also dead (JPMoresmau/scion-class-browser@572cc2c1177bdaa9558653cc1d941508cd4c7e5b) and seems to have trouble building as early as GHC 7.8.2 (JPMoresmau/scion-class-browser#19) -- remove it
    - [ ] dev-lang/ajhc likewise (top of http://ajhc.metasepi.org/) in favor of JHC, the last Hackage version is from 2013, and the GHC 8.6.5 can't build the dependency on `DrIFT` (unsurprising, since it asks for >=ghc-*6.10.4*) -- much as I hate to thin the field of compilers even further, probably time for it to be removed as well
  - [ ] hgettext (also needs =base-4.12.0.0 fixing: PR haskell-hvr/hgettext#17)
  - [x] pointfree (seems to just need a bounds bump: PR bmillwood/pointfree#33)
- [ ] Unmask the new versions of:
  - [x] <haskell-src-exts-1.22
  - [x] <haskell-src-exts-simple-1.22
  - [x] hlint
  - ~~<hoogle-5.0.17.13~~ 5.0.18 is available now

**Comment by pbarill** [comment]
Great analysis. It simplifies a fairly complicated issue. I had a go with a few items.

**Comment by ag-eitilt** [comment]
Glad to help!  This is certainly not meant as a "Y'all need to do this" -- I'll probably take a look into some of these soon myself, what with being stuck at home at the moment -- but in the mean time it's nice to see some boxes getting marked.

**Comment by solpeth** [comment]
`haskell-src-exts` is also in maintenance mode at this point anyway, so migrating our packages to use the latest versions should hopefully be the last time we need to deal with this sort of pain for this package.

**Comment by pbarill** [comment]
Right now there is a `haskell-src-exts-1.23` available on hackage, but there is next to nothing that plays with it, so not worth making an ebuild. Looks like it will never get there if things move away toward `ghc-lib-parser` and the rest just remains abandoned.

**Comment by solpeth** [comment]
Similar to what we've done with `network`, would slotting `haskell-src-exts` (e.g. SLOT="1.21/${PV}") help in this instance?

It doesn't automatically work. But it mostly worked with porting to `network-3`.

**Comment by solpeth** [comment]
Following my last comment, I'm currently having a lot of success with a slotted `haskell-src-exts`. I'll keep testing it, and push the changes when it seems solid enough.

**Comment by solpeth** [comment]
`derive` builds with slotted `haskell-src-exts`. Porting shouldn't be necessary, especially for an unmaintained package.

**Comment by solpeth** [comment]
`hgettext` needs patching for `cabal-2.4`. It seems trivial. But, nothing much depends on `hgettext` either, so I'm not sure it's worth the effort.

**Comment by solpeth** [comment]
@pbarill @ag-eitilt let me know if you come across any build failures resulting from `haskell-src-exts` being slotted. I'm only running into already existing issues, like incompatibilities with `base-4.12`.

As for `haskell-src-exts`, it seems happy with being slotted so far.

**Comment by hololeap** [comment]
`beam-migrate-cli` is dead, so you can check that off. What else is needed? Unmasking these three packages is showing no issues so far on my system.

**Comment by ezzieyguywuf** [comment]
I think `haskell-src-exts-1.22` may be ready to unmask, but we may need to keep `haskell-src-exts-1.23` masked, or see if these packages work with the newer version

- [ ] diagrams-builder-0.8.0.5-r1
- [ ] hlint-2.2.4
- [ ] stylish-haskell-0.9.4.4
- [ ] hprotoc-2.4.13

I'll run some tests on my machine with 1.22 and see how it goes...

**Comment by ezzieyguywuf** [comment]
This was closed on accident by github automatically, I think.
